name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker pull jaydenlee2019/mynodequery:latest
        docker tag jaydenlee2019/mynodequery:latest rg.fr-par.scw.cloud/funcscwscalewayaiynf5hy/mynodequery:latest
        docker login rg.fr-par.scw.cloud/funcscwscalewayaiynf5hy -u nologin -p ${{ secrets.DEPLOY_TOKEN }}
        docker push rg.fr-par.scw.cloud/funcscwscalewayaiynf5hy/mynodequery:latest
